### ISSUE TITLE
(9) As an instructor, I want to be able to reuse questions from previous semester so I do not have to rewrite old ones.

### ISSUE THREAD

**Issue by kreatz-gatech** [jds2017/ALRails#12] opened 2017-05-30 22:33 UTC
As an instructor, I want to be able to reuse questions from previous semester so I do not have to rewrite old ones.

**Comment by jensptan** [comment] 2017-06-22 15:57
Duplicate of searching for questions.

**Closed by jensptan** 2017-06-22 15:57 UTC
Labels: duplicate
